import { defineConfig } from 'vite';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { execSync } from 'node:child_process';

// What is running: the build's time and commit, shown next to the About link and used for the cache name.
const STAMP = new Date().toISOString();
function commit() {
  try {
    const sha = (process.env.GITHUB_SHA ?? execSync('git rev-parse HEAD').toString()).trim().slice(0, 7);
    const dirty = !process.env.GITHUB_SHA && execSync('git status --porcelain').toString().trim() !== '';
    return sha + (dirty ? '+' : '');
  } catch {
    return 'unknown';
  }
}
const BUILD = `${STAMP.slice(0, 16).replace('T', ' ')} UTC · ${commit()}`;

// Precaches the whole build so the spike runs offline once loaded from a secure origin.
// The cache name carries a build stamp, so a new build replaces the old cache when the phone is online.
function offline() {
  let outDir;
  return {
    name: 'offline-precache',
    apply: 'build',
    configResolved(c) {
      outDir = join(c.root, c.build.outDir);
    },
    closeBundle() {
      const files = [];
      const walk = (d) => {
        for (const n of readdirSync(d)) {
          const p = join(d, n);
          if (statSync(p).isDirectory()) walk(p);
          else if (n !== 'sw.js') files.push(relative(outDir, p).split('\\').join('/'));
        }
      };
      walk(outDir);
      writeFileSync(
        join(outDir, 'sw.js'),
        `// Generated by vite.config.js; do not edit.
const CACHE = 'spike-${STAMP}';
const FILES = ${JSON.stringify(['./', ...files])};

self.addEventListener('install', (e) => {
  // addAll fails the install if any file is missing, so a half-cached build never activates.
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit ?? fetch(e.request)),
  );
});
`,
      );
    },
  };
}

// A relative base lets the same build run from any path (GitHub Pages serves a repository under /<name>/).
export default defineConfig(({ command }) => ({
  base: './',
  plugins: [offline()],
  define: { __BUILD__: JSON.stringify(command === 'build' ? BUILD : 'dev server') },
  server: { host: true, port: 5173 },
  preview: { host: true, port: 4173 },
}));
